[project]
name = "comfyui_headless"
version = "0.2.3"
description = "A headless server for comfyui in the cloud"

[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]